# Generated by Django 5.2.11 on 2026-03-19 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bruker_produkt_alter_todoitem_id_bestilling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=150)),
                ('beskrivelse', models.TextField(blank=True)),
                ('dato', models.DateTimeField()),
                ('deltakere', models.ManyToManyField(blank=True, related_name='aktiviteter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
